name: Calc
on:
  push:
    branches:
    - main

jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Git repository
        uses: actions/checkout@v4
      
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: 'pypy3.10'

      - name: Run test app
        run: python3 test_math_operations.py
